"""add source_type and file_name to org_knowledge_docs

Revision ID: 847b88985b83
Revises: c3d4e5f6a7b8
Create Date: 2026-05-22 13:36:51.866956

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '847b88985b83'
down_revision: Union[str, Sequence[str], None] = 'c3d4e5f6a7b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('org_knowledge_docs', sa.Column('source_type', sa.String(length=20), nullable=True))
    op.add_column('org_knowledge_docs', sa.Column('file_name', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('org_knowledge_docs', 'file_name')
    op.drop_column('org_knowledge_docs', 'source_type')
    # ### end Alembic commands ###
